// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// optim_rcpp
List optim_rcpp(const arma::rowvec par, const arma::mat X, const arma::rowvec Y, const double lambda, const arma::rowvec theta);
RcppExport SEXP _bamboo_optim_rcpp(SEXP parSEXP, SEXP XSEXP, SEXP YSEXP, SEXP lambdaSEXP, SEXP thetaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::rowvec >::type par(parSEXP);
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type theta(thetaSEXP);
    rcpp_result_gen = Rcpp::wrap(optim_rcpp(par, X, Y, lambda, theta));
    return rcpp_result_gen;
END_RCPP
}
// emWithoutL1
List emWithoutL1(const arma::mat X, const arma::rowvec Y, const arma::rowvec par, const double lambda, const double conv);
RcppExport SEXP _bamboo_emWithoutL1(SEXP XSEXP, SEXP YSEXP, SEXP parSEXP, SEXP lambdaSEXP, SEXP convSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type par(parSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type conv(convSEXP);
    rcpp_result_gen = Rcpp::wrap(emWithoutL1(X, Y, par, lambda, conv));
    return rcpp_result_gen;
END_RCPP
}
// emWithL1
List emWithL1(const arma::mat X, const arma::rowvec Y, const double lambda, const double conv);
RcppExport SEXP _bamboo_emWithL1(SEXP XSEXP, SEXP YSEXP, SEXP lambdaSEXP, SEXP convSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::rowvec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const double >::type conv(convSEXP);
    rcpp_result_gen = Rcpp::wrap(emWithL1(X, Y, lambda, conv));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_bamboo_optim_rcpp", (DL_FUNC) &_bamboo_optim_rcpp, 5},
    {"_bamboo_emWithoutL1", (DL_FUNC) &_bamboo_emWithoutL1, 5},
    {"_bamboo_emWithL1", (DL_FUNC) &_bamboo_emWithL1, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_bamboo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
