## quiets concerns of R CMD check re:no binding global varaible or function
if (getRversion() >= "2.15.1") {
    utils::globalVariables(c(
        "GENEID",
        "PC1", "PC2", "TXNAME",
        "annotationTxId", "chr", "chr.rc",
        "compatible", "confidenceType", "endMatch",
        "eqClass", "eqClassReadCount", "equal",
        "estimates", "exon_rank", "feature",
        "geneCount", "geneId", "gene_id", "gene_sid",
        "groupVar", "group_name", "intronEnds",
        "intronStarts", "newGeneClass", "newTxClass",
        "nobs_stored", "queryElementsOutsideMaxDist",
        "queryHits.x", "queryHits.y", "readClassId",
        "readCount", "read_class_id", "read_class_sid",
        "read_class_sid_stored", "rowMaxs", "rowMins",
        "runname", "seqlengths", "startMatch", "strand.rc",
        "subjectCount", "subjectElementsOutsideMaxDist",
        "subjectHits.y", "sum_nobs", "txId", "txNumberFiltered",
        "tx_id", "tx_name", "tx_sid", "uniqueEndLengthQuery",
        "uniqueLengthQuery", "uniqueLengthSubject",
        "score","frame","dist","nobs","index",
        "uniqueStartLengthQuery", "value", "valueGene", "valueGeneCPM",
        "variable", "junctionMatchList", "readClass.file", 
        "start.ptm", "verbose", ".insertGaps", ".","subjectList",
        "CPM", "FullLengthCounts", "PartialLengthCounts", "UniqueCounts",
        "annotatedEnd", "annotatedJunction", "annotatedStart", "aval", 
        "dObs", "endScore", "firstExonWidth", "fullTx", "junctionEndName",
        "junctionStartName", "minEquiRC", "multi_align", "par_status",
        "rc_width", "spliceMotif", "startScore", "theta", "totalWidth",
        "txNumber", "txNumberExpected", "tx_id_new", "tx_len", "tx_ori",
        "counts","intersectWidth", "newGeneId", "newTxId", 
        "newGeneId.merge", "newTxId", "newGeneId","nTx","geneReadCount",
        "startSD","endSD","readCount.posStrand","alignmentStrand","newExonId",
        "newExonId.merge","newGeneId","readStart","readEnd","novelGene",
        "numReads","numExons","numRCs","geneReadProp","numAstart", "numAend",
        "numTstart","numTend","tx_strand_bias", "maxTxScore", 
        "NSampleReadCount", "NSampleReadProp", "NSampleTxScore", 
        "NSampleReadCount.combined", "NSampleReadCount.new", 
        "NSampleReadProp.combined", "NSampleReadProp.new", 
        "NSampleTxScore.combined", "NSampleTxScore.new", "maxTxScore.combined",
        "maxTxScore.new" ,"txScore" ,"row_id" ,"txScore", "sample_id", 
        "sample_name", "txScore", "readCount_tmp", "group", "row_id", "rowID", 
        "sumReadCount", "maxTxScore", "NSampleReadCount", "NSampleReadProp", 
        "NSampleTxScore", "geneid", "readIds", "readId", "anyCompatible","seqname"
    ))
}
