# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Create likelihood objective function to estimate bias parameters
#'
#' @param par A row vector of bias parameters for each read class
#' @param X sampling probability matrix, (i,j) = 1 if read class j is potentially from transcript i, otherwise 0
#' @param Y observed number of reads for each read class j
#' @param lambda, the tuning parameter for bias estimation
#' @param theta estimates for isoform expression
NULL

#' Create likelihood objective function to estimate bias parameters
#'
#' @param par A row vector of bias parameters for each read class
#' @param X sampling probability matrix, (i,j) = 1 if read class j is potentially from transcript i, otherwise 0
#' @param Y observed number of reads for each read class j
#' @param lambda, the tuning parameter for bias estimation
#' @param nzindex estimates for isoform expression
NULL

#' Optimization function for bias parameters
#'
#' @param par A row vector of bias parameters for each read class
#' @param X sampling probability matrix, (i,j) = 1 if read class j is potentially from transcript i, otherwise 0
#' @param Y observed number of reads for each read class j
#' @param lambda, the tuning parameter for bias estimation
#' @param theta estimates for isoform expression
optim_b_rcpp <- function(theta, X, Y, lambda, b) {
    .Call(`_bamboo_optim_b_rcpp`, theta, X, Y, lambda, b)
}

#' EM algorithm with L1-penalty
#'
#' @param X sampling probability matrix, (i,j) = 1 if read class j is potentially from transcript i, otherwise 0
#' @param Y observed number of reads for each read class j
#' @param lambda, the tuning parameter for bias estimation
#' @param conv convergence threshold of likelihoods
#' @export
em_theta <- function(X, Y, lambda, b, d, maxiter, conv) {
    .Call(`_bamboo_em_theta`, X, Y, lambda, b, d, maxiter, conv)
}

#' EM algorithm with L1-penalty
#'
#' @param X sampling probability matrix, (i,j) = 1 if read class j is potentially from transcript i, otherwise 0
#' @param Y observed number of reads for each read class j
#' @param lambda, the tuning parameter for bias estimation
#' @param conv convergence threshold of likelihoods
#' @export
emWithL1 <- function(X, Y, lambda, d, maxiter, conv) {
    .Call(`_bamboo_emWithL1`, X, Y, lambda, d, maxiter, conv)
}

#' Optimization function for bias parameters
#'
#' @param par A row vector of bias parameters for each read class
#' @param X sampling probability matrix, (i,j) = 1 if read class j is potentially from transcript i, otherwise 0
#' @param Y observed number of reads for each read class j
#' @param lambda, the tuning parameter for bias estimation
#' @param theta estimates for isoform expression
optim_thetaandb_rcpp <- function(est, X, Y, lambda, nzindex) {
    .Call(`_bamboo_optim_thetaandb_rcpp`, est, X, Y, lambda, nzindex)
}

#' EM algorithm with L1-penalty
#'
#' @param X sampling probability matrix, (i,j) = 1 if read class j is potentially from transcript i, otherwise 0
#' @param Y observed number of reads for each read class j
#' @param lambda, the tuning parameter for bias estimation
#' @param conv convergence threshold of likelihoods
#' @export
emWithoutL1 <- function(X, Y, lambda, nzindex, conv) {
    .Call(`_bamboo_emWithoutL1`, X, Y, lambda, nzindex, conv)
}

#' run_em
#'
#' @param XList sampling probability matrix, (i,j) = 1 if read class j is potentially from transcript i, otherwise 0
#' @param YList observed number of reads for each read class j
#' @param lambdaList, the tuning parameter for bias estimation
#' @param conv convergence threshold of likelihoods
#' @export
run_em <- function(XList, YList, lambdaList, d, maxiter, conv, nthr, display_progress = TRUE) {
    .Call(`_bamboo_run_em`, XList, YList, lambdaList, d, maxiter, conv, nthr, display_progress)
}

